### ISSUE TITLE
Error on deployed Next.js website

### ISSUE THREAD

**Issue by VaniaPopovic** [muxinc/upchunk#111]
Hey everyone,

I have started experiencing a weird bug that only shows up on a deployed website

![image](https://github.com/muxinc/upchunk/assets/17993952/1890f91f-dc35-4317-bd84-9bb280afebb7)

When running the project locally the problem does not arise. Do you know where it might be coming from?

I am using Upchunk v 3.2.0 & pnpm 8.5.1

Package.json
```
"dependencies": {
    // other unrelated deps
    "@mux/mux-node": "^7.3.0",
    "@mux/mux-player-react": "^1.11.0",
    "@mux/upchunk": "3.2.0",
    "next": "13.4.3",
    "swr": "^2.1.5",
    "ui": "workspace:*",
  },
  "devDependencies": {
    // other unrelated deps
    "tsconfig": "workspace:*",
    "typescript": "^5.1.1-rc"
  }
```

Code that fails:
```

import * as UpChunk from "@mux/upchunk";
 const startUpload = () => {
    setIsUploading(true);

    const upload = UpChunk.createUpload({
      endpoint: createUpload,
      file: file.file!,
    });

    upload.on("error", (err: any) => {
      console.log("Error in upload", err);
      setErrorMessage(err.detail.message);
    });
    upload.on("progress", (progress: any) => {
      setProgress(Math.floor(progress.detail));
    });
    upload.on("success", async () => {
      setIsPreparing(true);
    });
  };
```
My code is taken from the MUX example found here https://github.com/vercel/next.js/tree/canary/examples/with-mux-video
P.S I downgraded the library to 3.1.0 and the problem is no longer appearing on the production website.

**Comment by joviczarko** [comment]
Let's start with including upchuck into project. Give us that line.

**Comment by VaniaPopovic** [comment]
> Let's start with including upchuck into project. Give us that line.

I updated the intial post with more information

**Comment by Pierniki** [comment]
Hey, same issue here. App also deployed on vercel and code snippet pretty much the same.
`upload.on("progress", (progress: any) =>` event was returning `{ isTrusted: false }` object.
Downgrading to 3.1.0 also fixed the issue.

**Comment by cjpillsbury** [comment]
Could you try replacing
```js
import * as UpChunk from "@mux/upchunk";
```
with
```js
import { UpChunk } from "@mux/upchunk";
```
We'll want to investigate this further for sure, but maybe that will unblock?

**Comment by rawalrajen** [comment]
I have found the solution. I will create a PR to resolve this issue

**Comment by Aidurber** [comment]
@cjpillsbury [solution](https://github.com/muxinc/upchunk/issues/111#issuecomment-1563057481) worked for me

**Comment by Melvynx** [comment]
I've got exactly the same issue. I tested all the solutions but the version 3.0.2 gave me the same error **only after build**. In NextJS dev mode everything is okay... but not in production. 

<img width="476" alt="a6851a4f35c9b13a43209dfab62838664e9a0561598c704c1a4655d95652ea87" src="https://github.com/muxinc/upchunk/assets/56388157/d1f387c5-a3b6-455a-ad2c-23a33e9ee1a9"> 

I use NextJS 13 App router.

**Comment by donalffons** [comment]
I'm using the [sanity-plugin-mux-input](https://github.com/sanity-io/sanity-plugin-mux-input), which uses this project under the hood and I'm experiencing the same error. Things work fine in `dev`, but fail after `build`.

@cjpillsbury's solution also worked for me.

**Comment by mmvsk** [comment]
I just wanted to fill this bug.

Basically, it's an issue with ESbuild with the minimize flag, when the library is passed to Webpack.

Minimal reproduction: https://github.com/mmvsk/bug-upchunk-webpack (the output contains `null.includes(...)`

A reproduction of the ESBuild bug by itself: https://github.com/mmvsk/bug-esbuild-min-webpack

I'll post the PR now.

**Comment by mmvsk** [comment]
It is due to a bug with ESBuild. When compiled with the minification flag, and the code contains an export of a static class method, then passed to Webpack, it doesn't include previous constants (here status codes).

Minimal reproduction: https://github.com/mmvsk/bug-upchunk-webpack (output contains `null.includes(...)`

Reproduction of the ESBuild-x-Webpack bug: https://github.com/mmvsk/bug-esbuild-min-webpack

Removing minimize or exporting `createUpload` as a function solves the issue.

I'll post the PR now.
