### ISSUE TITLE
The video asset get auto deleted after 24 hours?

### ISSUE THREAD

**Issue by Osmanity** [muxinc/upchunk#113]
Im working with a project where as when I create a video asset from my course platform nextjs project the video asset get deleted automatically after 24 hours which is very strange?

Here is the api activity  logs from mux dashboard:

![image](https://github.com/muxinc/upchunk/assets/83875991/43663f1f-d8f6-4b8d-9e50-d56d051def5d)

**Comment by mmcc** [comment]
Hi there! If you're still in test mode (either by not having a credit card on file yet or manually specifying `test: true` in asset creation, then this is expected. From the docs re: `test` mode: 

>>> Marks the asset as a test asset when the value is set to true. A Test asset can help evaluate the Mux Video APIs without incurring any cost. There is no limit on number of test assets created. Test asset are watermarked with the Mux logo, limited to 10 seconds, deleted after 24 hrs.
