### ISSUE TITLE
[Bug] Failure to Handle 'Range' Response Header in Chunked Uploads to GCS

### ISSUE THREAD

**Issue by skidder** [muxinc/upchunk#124]
Hello Mux Team! 👋

I've encountered an issue with `upchunk`'s handling of resumable chunked uploads to Google Cloud Storage (GCS). Specifically, the library does not appear to process the `Range` header in HTTP 308 responses correctly, potentially leading to incomplete uploads despite successful transmission of all data chunks.

**Current Behavior:**
- When uploading chunks (other than the last one) to GCS, the expected server response for a successful upload is `308 Resume Incomplete`. This response includes a `Range` header, as specified in the [GCS documentation](https://cloud.google.com/storage/docs/performing-resumable-uploads#chunked-upload).
- The `upchunk` library currently does not evaluate the `Range` header in these 308 responses. Consequently, it might continue transmitting the full range of bytes without recognizing that the upload has not been completed successfully on the server's end.
- There is also a lack of verification to ensure the final chunk results in the object being marked as complete (typically indicated by an HTTP 200 or 201 response, and specifically _not_ an HTTP 308). This omission could lead clients to mistakenly believe the upload was successful when it wasn't.

**Expected Behavior:**
- The library should use the upper value in the `Range` header of each 308 response to accurately determine the starting point for each successive chunk. Alternatively, chunks that were not fully received could be sent again in their entirety.
- After transmitting the final chunk, the library should verify the server's response to confirm that the upload is indeed complete and successful.

**Suggested Fix:**
- Implement logic to parse and use the `Range` header in 308 responses to adjust the starting byte position for subsequent chunks, or use the existing retry logic to resend any chunks that were not fully received.
- Add a check after the final chunk is sent to verify the response status (HTTP 200 or 201) to confirm the successful completion of the upload.

I believe that fixing these issues should improve the reliability of chunked uploads to GCS, or any other service that makes use of the response `Range` header. I'm happy to submit a PR or collab on a solution!

Thanks!

**Comment by cjpillsbury** [comment]
👋 Hey @skidder! Taking a peep at the PR ASAP, but broadly this ask makes sense to me.

**Comment by cjpillsbury** [comment]
@skidder you should be good to go! https://www.npmjs.com/package/@mux/upchunk/v/3.3.1 We can re-open/create a new issue if there are any problems.
