### ISSUE TITLE
[Feature Request] Response object inside the 'error' event

### ISSUE THREAD

**Issue by mr-sanders** [muxinc/upchunk#128]
It seems sensible to provide access to the response object within the callback of the 'error' event. For instance, this would be useful if we need to handle specific server issues such as insufficient storage or conflicts. Currently, we only receive a message with the status code.

**Comment by cjpillsbury** [comment]
Hey @mr-sanders. This sounds reasonable to me and the PR looks similarly reasonable. Let me check in with a few folks before merging/releasing, but I suspect this will make it in soon. Thanks for the feedback and especially the contrib!

**Comment by cjpillsbury** [comment]
resolved by #129
