### ISSUE TITLE
returning the asset ID on success

### ISSUE THREAD

**Issue by bufordtaylor** [muxinc/upchunk#143]
It would be useful to return the asset ID on successful upload so mux customers won't need to write webhook code to get the asset ID, and then backend code to broadcast to the front end, and front end code to listen to an update so we can finally simply show the asset that was just uploaded.

**Comment by philcluff** [comment]
Hey @bufordtaylor, thanks for the feedback. 

We can't currently return this ID due to limited functionality on the underlying storage that Upchunk uses (Google Cloud storage)

I'll make sure to record this product feedback for when we're able to do deeper work on Direct Uploads.

Thanks!
