### ISSUE TITLE
How to handle errors when get upload URL?

### ISSUE THREAD

**Issue by martinbean** [muxinc/upchunk#148]
I’m integrating UpChunk into an app. I have a callback to generate and return an upload URL:

```ts
const getUploadUrl = () => axios.post('/uploads').then((response) => response.data.url);
```

However, if that endpoint (`/uploads`) throws an error (which it does if the authenticated user has not verified their email address, as I don’t want people signing up with a fake email address and incurring costs for me by uploading gigabytes of video), then UpChunk also errors:

```
Uncaught (in promise) AxiosError {message: 'Request failed with status code 403', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
```

I’ve tried wrapping the Axios call in a `try`/`catch` block, I’ve tried wrapping the `UpChunk.createUpload` method call in a `try`/`catch` block, but I can’t find a way of actually handling an error that may come from the generate endpoint function.

How should I be handling potential rejections from my `getUploadUrl` function?

**Comment by mmcc** [comment]
Hmm I think there's definitely a question for how we want to handle the failure one level higher, but have you tried adding a `.catch` to your axios call?

```javascript
const getUploadUrl = () => axios.post('/uploads').then((response) => response.data.url).catch(() => console.log("oh nos"));
```

**Comment by martinbean** [comment]
@mmcc I just got around it by only creating the upload after resolving the upload URL itself. Basically:

```js
getUploadUrl().then((url) => {
    const upload = UpChunk.createUpload({
        endpoint: url,
        file: picker.files[0],
        chunkSize: 30720, // Uploads the file in ~30 MB chunks
    });

    // ...
});
```

This allows me to handle any errors from generating the upload URL before creating an UpChunk instance.
