### ISSUE TITLE
tus comparison

### ISSUE THREAD

**Issue by srhyne** [muxinc/upchunk#16]
Hi there! Upchunk looks like a fantastic project. Bravo. Could anyone shed light on how Upchunk compares to tus? Does Mux support tus?

**Comment by GeneticGenesis** [comment]
Hey @srhyne,

Thanks for the kind words. Currently Mux exposes Google Cloud Storage URLs when you generate a Direct Upload, which don't currently support tus as an upload protocol, hence this project is closely tied to Google's resumable signed URL implementation.

Thanks!

**Comment by srhyne** [comment]
Thank you @GeneticGenesis!
