### ISSUE TITLE
`progress` event jumps backwards

### ISSUE THREAD

**Issue by dylanjha** [muxinc/upchunk#30]
Notice in this screenshot the progress events go from `3` to `49`, then jumps backwards to `33`, then progresses again to `82`, then jumps back to `67`.

![progress-evt_2020-08-17_18-00-47](https://user-images.githubusercontent.com/764988/90458615-bd6c9880-e0b3-11ea-9b8a-abb2a41a2538.png)

----

In this example. my source file is 10.6 MB. At the default chunk size `5120` that will be 3 chunks. Because this backwards jump happens at 33 and 67, it seems like some funny business going with the progress event that gets emitted at the boundary of a new chunk.

Here's a video of the bug: https://stream.new/v/EBPMDDqXrxsT01ToQwBbVx2027dx5dqucOoCxkXcCMEIk

**Comment by damechen** [comment]
I hit the same issue. I am using upchunk@2.0.0. It also jumped back to 33 and 67.

Here is the video: https://recordit.co/dAqIMlufDc

**Comment by marcelfahle** [comment]
Same over here, although less apparent on bigger file sizes, where it jumps only 1% or so.

**Comment by michaellimair** [comment]
I tried to fix this bug, perhaps the original authors or contributors can have a look. Thanks!

https://github.com/muxinc/upchunk/pull/43

**Comment by dylanjha** [comment]
closed in #43 !
