### ISSUE TITLE
chunk upload fails towards the end and errors out - but video is successfully uploaded

### ISSUE THREAD

**Issue by armouti** [muxinc/upchunk#31]
Chunks seem to always fail to upload towards the end, somewhere between 80% and 95% (depending on the size of the video), and then the error event eventually gets thrown, but in the dashboard I can see the video has successfully uploaded.
Here's a screenshot:
<img width="709" alt="Screenshot 2020-08-20 at 02 00 24" src="https://user-images.githubusercontent.com/37476568/90704914-a54e7200-e289-11ea-822a-dc594f8c8483.png">

**Comment by armouti** [comment]
solved by @GeneticGenesis, the fix was to use the `cors_origin` argument when creating the upload URL, which I was omitting.

**Comment by GeneticGenesis** [comment]
Thanks @armouti !
