### ISSUE TITLE
dist not being created in 2.1.0

### ISSUE THREAD

**Issue by marcelfahle** [muxinc/upchunk#39]
Hey guys, I just noticed that the `dist` folder is missing after installing the latest release:

<img width="1387" alt="Screen Shot 2020-11-30 at 2 53 45 PM" src="https://user-images.githubusercontent.com/181004/100620845-302a1880-331f-11eb-9b86-b55c59f8c6c0.png">

Cheers,
Marcel

**Comment by GeneticGenesis** [comment]
Hey @marcelfahle, thanks, we'll take a look today

**Comment by mmcc** [comment]
Hey @marcelfahle, sorry about that, went ahead and manually pushed an updated version while I figure out what in the world is going on with the new Github Action :(

**Comment by marcelfahle** [comment]
No worries and thanks! I just noticed it when I did a fresh install this morning, went back to 2.0 for the time being, but will upgrade again later 😄
