### ISSUE TITLE
tus support

### ISSUE THREAD

**Issue by kasperkamperman** [muxinc/upchunk#42]
How does this is different from TUS? Any reason that mux doesn't support that protocol?

https://tus.io/
https://github.com/tus

**Comment by GeneticGenesis** [comment]
Hey @kasperkamperman, Mux uses Google Cloud Storage for its Direct Upload URLs, as such this library is primarily compatible with those storage URLs. 

TUS requires intermediary servers to write to object stores like S3, GCS or others, which would be extra infrastructure for us to deploy and maintain. 

That said, there's no reason for UpChunk not to support TUS backends, but it's not a priority for us right now.

Thanks!

**Comment by armouti** [comment]
@GeneticGenesis TUS is just a video upload protocol regardless if done server side or client side. Nonetheless, the main (community supported) client-side TUS client has many issues is currently not in a great shape (https://github.com/tus/tus-js-client)
