### ISSUE TITLE
How to handle cleanup?

### ISSUE THREAD

**Issue by MartinMalinda** [muxinc/upchunk#44]
Hi!

Upchunk works well for me, but our app has some performance issues if people upload multiple large files in successions. Upchunk is probably not to blame, but I'm doublechecking. I can see that there's no `destroy()` method. When I'm unmounting the component that uses Upchunk, I'm only calling `.abort()`. 

But calling `.abort()` will not remove event listeners, nor other state from the class. Is there other way how to cleanup after Upchunk? Thanks!

**Comment by mmcc** [comment]
Hi there!

I'm not totally sure what we can do here, I'll need to think on it a bit. We don't actually attach anything to the DOM itself (aside from some connectivity listeners at the `window` level), so I don't _think_ there's an issue there. As far as cleaning up class state itself goes, if you're aborting entirely I think your best bet is just deleting the UpChunk instance in question.

**Comment by mmcc** [comment]
@MartinMalinda Closing this issue since I think we need a little more info on whether or not there's something we need to change, but ping this thread and we'll reopen!
