### ISSUE TITLE
Cancel upload

### ISSUE THREAD

**Issue by phuclh** [muxinc/upchunk#60]
Is there a way to cancel the upload? I only see `success` and `failed` events.

Thank you!

**Comment by mmcc** [comment]
`pause` will typically do what you want, but looks like [`abort`](https://github.com/muxinc/upchunk/blob/master/src/upchunk.ts#L108-L111) never made it onto the readme! `abort` pauses the upload, but also cancels the current, in-flight request.

Is there something else you're looking for around cancellation?

**Comment by mmcc** [comment]
Just merged #61 which adds a note about `abort` and describes how cancellation works. 

Thanks for the heads up.

**Comment by phuclh** [comment]
Thank you for the quick support 👯
