### ISSUE TITLE
Infinite recursion from old event-target-shim dependency

### ISSUE THREAD

**Issue by helloandrewpark** [muxinc/upchunk#62]
An [issue from the event-target-shim](https://github.com/mysticatea/event-target-shim/issues/26) dependency causes the browser process to get stuck in an infinite recursion when an event is dispatched. This prevents uploads from succeeding and eventually the browser tab crashes. This was fixed in 6.0.2, could you please upgrade?

note: i was able to get this working by changing package.json with
```
"typescript": "^4.1.3",
...
"event-target-shim": "^6.0.2",
```

**Comment by ramiel** [comment]
Has this been released? Version `2.2.2` still has `event-target-shim@4.0.3` as dependency, making it unusable
