### ISSUE TITLE
How do we get asset_id of video which is uploaded

### ISSUE THREAD

**Issue by RizwanAslam** [muxinc/upchunk#64]
On success callback, there is nothing passed to that method instead of the error object.  I am confused about how we will get the URL of the uploaded asset which I will use to preview the video. 

// subscribe to events
upload.on('success', err => {
  console.log("Wrap it up, we're done here. 👋");
});

**Comment by dylanjha** [comment]
Hi @RizwanAslam thanks for reaching out. Good question -- let me help clarify. The short answer is that after the upload `success` fires you will need to do one of two things:

- Make a request from your client to your server and from your server make a request to Mux with the `upload_id`
- Wait for the Mux Webhook `video.upload.asset_created` (more [details here](https://docs.mux.com/guides/video/listen-for-webhooks#upload-events)) -- this will contain the full `upload` object which will have an `asset_id` property.

^ Either of those methods is valid.

----

It sounds like you understand this bit -- but to clarify the relationship between Mux **Uploads** and Mux **Assets** for anyone else that may come across this:

Mux **Upload**

- This gets created on the serverside and gives you an "upload URL" by making the request: `POST /uploads`
- The upload itself has several properties:`id`, `url`, `status`, `new_asset_settings`, `error`
- Use the `url` property with Upchunk to perform the upload -- it sounds like you got this far
- When the upload is complete, either `GET /uploads/:id` [API Reference](https://docs.mux.com/api-reference/video#operation/get-direct-upload) or listen for the `video.upload.asset_created` Webhooks
- At this point in time now that the upload is complete, the upload will have an `asset_id` property.

Mux **Asset**

- Use the `asset_id` property from the completed upload to fetch the asset
- GET `/assets/:id`: [API Reference](https://docs.mux.com/api-reference/video#operation/get-asset)
- The asset itself has a `status` (`"preparing"`, `"ready"`, `"errored"`), `playback_ids`, `aspect_ratio, an `upload_id`, etc.
- Be ready to handle all 3 statusus in your application. When the upload is complete the asset will start in the `"preparing"` state and assuming a valid video file as been uploaded then it will transition to `"ready"`. If the file was not a video file, or happens to be invalid for another reason then the asset will be in the `"errored"` status. 

Hopefully that clarifies the relationship between **Uploads** and **Assets**. Here's [a guide](https://docs.mux.com/guides/video/upload-files-directly) that might be helpful too.

Let us know if you're still stuck and we'd be happy to help!

**Comment by RizwanAslam** [comment]
Hi @dylanjha, yup I got it now. Thank you very much for your quick response. Cheers
