### ISSUE TITLE
'multipart/form-data' file data is not passing to controller

### ISSUE THREAD

**Issue by Manirajss** [muxinc/upchunk#69]
Hi ,
       I am using upchunk npm for react for file upload. I am trying to upload using 'Content-Type': 'multipart/form-data'. File data not passing to server(controller). Please suggest how to use 'Content-Type': 'multipart/form-data' .

**Comment by philcluff** [comment]
Hi @Manirajss, this isn't currently supported - upchunk is designed to work with Mux Direct Upload URLs as documented in the readme, which currently implements the Google Cloud Storage upload scheme.

We don't have any immediate plans to make this library compatible with any other upload schemes, but if we do, we'll keep this in mind.

Thanks.
